let progresBack = document.querySelector('#progresBack'),
    future = document.querySelector('#future'),
    allQuiz = document.querySelector('#allQuiz'),
    geniralTime = document.querySelector('#geniralTime'),
    quizTime = document.querySelector('#quizTime'),
    fname = document.querySelector('#fname'),
    quiz = document.querySelector('#quiz'),
    quiz2 = document.querySelector('#quiz2'),
    repys = document.querySelector('#repys');
let variant1 = document.querySelector('#variant1'),
    variant2 = document.querySelector('#variant2'),
    variant3 = document.querySelector('#variant3'),
    variant4 = document.querySelector('#variant4'),
    variant5 = document.querySelector('#variant5'),
    variant6 = document.querySelector('#variant6');
let aboutQuiz = document.querySelector('#aboutQuiz'),
    leave = document.querySelector('#leave'),
    next = document.querySelector('#next');
    